#!/usr/bin/env python3
"""Read the C++ files in implementations/ and emit docs/code-data.js.

This bakes the source into the static site so the Code Lab page works both
offline (file://) and on GitHub Pages, without any runtime fetch. Run it
whenever the implementations change; CI runs it automatically before deploy.
"""
import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
IMPL = ROOT / "implementations"
OUT = ROOT / "docs" / "code-data.js"

# Folders in learning order (anything not listed falls to the end, alphabetically).
FOLDER_ORDER = [
    "arrays", "linked_list", "stack_queue", "searching", "sorting",
    "recursion", "trees", "heap", "trie", "graph", "dp",
]
FOLDER_LABELS = {
    "arrays": "Arrays", "linked_list": "Linked Lists", "stack_queue": "Stacks & Queues",
    "searching": "Searching", "sorting": "Sorting", "recursion": "Recursion",
    "trees": "Trees", "heap": "Heaps", "trie": "Tries", "graph": "Graphs", "dp": "Dynamic Programming",
}


def first_comment(text: str) -> str:
    """Use the first // line as the file's one-line description."""
    for line in text.splitlines():
        s = line.strip()
        if s.startswith("//"):
            return s.lstrip("/ ").strip()
        if s and not s.startswith("//"):
            break
    return ""


def folder_rank(folder: str) -> int:
    return FOLDER_ORDER.index(folder) if folder in FOLDER_ORDER else len(FOLDER_ORDER)


def main() -> None:
    files = []
    for path in sorted(IMPL.rglob("*.cpp")):
        rel = path.relative_to(IMPL).as_posix()          # e.g. "arrays/two_pointers.cpp"
        folder = rel.split("/")[0] if "/" in rel else ""
        code = path.read_text()
        files.append({
            "path": rel,
            "folder": folder,
            "folderLabel": FOLDER_LABELS.get(folder, folder or "Misc"),
            "name": path.name,
            "desc": first_comment(code),
            "code": code,
        })

    files.sort(key=lambda f: (folder_rank(f["folder"]), f["folder"], f["name"]))

    readme = ""
    readme_path = IMPL / "README.md"
    if readme_path.exists():
        readme = readme_path.read_text()

    payload = {"files": files, "readme": readme}
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(
        "// AUTO-GENERATED by scripts/gen_code_data.py — do not edit by hand.\n"
        "window.CODE_DATA = " + json.dumps(payload, ensure_ascii=False) + ";\n"
    )
    print(f"Wrote {OUT.relative_to(ROOT)} with {len(files)} files.")


if __name__ == "__main__":
    main()
